import Head from 'next/head';
import Overlay from '../components/overlay';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Belong</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Overlay />
		</div>
	);
}
